// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLYG8yXXE-1wAyq68VvyGveea1EOChmS4',
    appId: '1:216741808857:android:61ad1f0db025167fcc8cc8',
    messagingSenderId: '216741808857',
    projectId: 'chat-app-75b20',
    databaseURL:
        'https://chat-app-75b20-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-75b20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23rZrc-TMIw0W4wGEv7eIfkR7jYJdc3s',
    appId: '1:216741808857:ios:d727c3a731a80bfdcc8cc8',
    messagingSenderId: '216741808857',
    projectId: 'chat-app-75b20',
    databaseURL:
        'https://chat-app-75b20-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-75b20.appspot.com',
    iosBundleId: 'com.attraxia.chatapp',
  );
}
